version: '3'
services:
    web:
        build:
            context: ./app
        ports:
            - "80:5000"
        networks:
            - frontend
        depends_on:
            - redisdb
        environment:
            - REDIS_HOST=redisdb
            - REDIS_PORT=6379
    redisdb:
        image: redis
        ports:
            - "6379"
        networks:
            - frontend
        volumes:
            - redis_data:/data
networks:
    frontend:
volumes:
    redis_data:
